"use strict";(self.webpackChunkavalonia_docs=self.webpackChunkavalonia_docs||[]).push([[89493],{85020:(e,n,t)=>{t.r(n),t.d(n,{assets:()=>c,contentTitle:()=>r,default:()=>h,frontMatter:()=>i,metadata:()=>s,toc:()=>d});var o=t(85893),a=t(11151);const i={id:"unhandled-exceptions",title:"Unhandled Exceptions"},r=void 0,s={id:"getting-started/unhandled-exceptions",title:"Unhandled Exceptions",description:"Avalonia does not offer any mechanism to handle exceptions globally and mark this as handled. The reason is, that one cannot know if the exception has been handled correctly and therefore the application may be in an invalid state. Instead it's highly recommend to handle exceptions locally if these can be handled by your application. That said it is still a good idea to log any unhandled exception for further support and debugging.",source:"@site/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.10.x/getting-started/unhandled-exceptions.md",sourceDirName:"getting-started",slug:"/getting-started/unhandled-exceptions",permalink:"/avalonia-docs/zh-Hans/docs/0.10.x/getting-started/unhandled-exceptions",draft:!1,unlisted:!1,editUrl:"https://github.com/AvaloniaUI/avalonia-docs/tree/main/i18n/zh-Hans/docusaurus-plugin-content-docs/version-0.10.x/getting-started/unhandled-exceptions.md",tags:[],version:"0.10.x",frontMatter:{id:"unhandled-exceptions",title:"Unhandled Exceptions"},sidebar:"documentationSidebar",previous:{title:"Logging Errors and Warnings",permalink:"/avalonia-docs/zh-Hans/docs/0.10.x/getting-started/logging-errors-and-warnings"},next:{title:"Application Lifetimes",permalink:"/avalonia-docs/zh-Hans/docs/0.10.x/getting-started/application-lifetimes"}},c={},d=[{value:"Logging",id:"logging",level:2},{value:"The global try-catch",id:"the-global-try-catch",level:2},{value:"Exceptions from another thread",id:"exceptions-from-another-thread",level:2},{value:"Exceptions from Reactive UI",id:"exceptions-from-reactive-ui",level:2}];function l(e){const n={a:"a",code:"code",h2:"h2",p:"p",pre:"pre",...(0,a.a)(),...e.components};return(0,o.jsxs)(o.Fragment,{children:[(0,o.jsx)(n.p,{children:"Avalonia does not offer any mechanism to handle exceptions globally and mark this as handled. The reason is, that one cannot know if the exception has been handled correctly and therefore the application may be in an invalid state. Instead it's highly recommend to handle exceptions locally if these can be handled by your application. That said it is still a good idea to log any unhandled exception for further support and debugging."}),"\n",(0,o.jsx)(n.h2,{id:"logging",children:"Logging"}),"\n",(0,o.jsxs)(n.p,{children:["We recommend to log exceptions to the console, a file or anywhere else. There are several logging libraries available out there, for example ",(0,o.jsx)(n.a,{href:"https://serilog.net",children:"Serilog"})," and ",(0,o.jsx)(n.a,{href:"https://nlog-project.org",children:"NLog"}),"."]}),"\n",(0,o.jsx)(n.h2,{id:"the-global-try-catch",children:"The global try-catch"}),"\n",(0,o.jsxs)(n.p,{children:["You can catch any exception from the main thread, which is also the UI thread in Avalonia, in your ",(0,o.jsx)(n.code,{children:"Program.cs"}),"-file. To do so we just wrap the entire ",(0,o.jsx)(n.code,{children:"void Main"})," in a ",(0,o.jsx)(n.code,{children:"try"})," and ",(0,o.jsx)(n.code,{children:"catch"})," block. In the ",(0,o.jsx)(n.code,{children:"catch"})," block you can log the error, inform the user, send the log file or restart the application."]}),"\n",(0,o.jsx)(n.pre,{children:(0,o.jsx)(n.code,{className:"language-csharp",children:'// File: Program.cs\n\npublic static void Main(string[] args)\n{\n    try\n    {\n        // prepare and run your App here\n        BuildAvaloniaApp()\n            .StartWithClassicDesktopLifetime(args);\n    }\n    catch (Exception e)\n    {\n        // here we can work with the exception, for example add it to our log file\n        Log.Fatal(e, "Something very bad happened");\n    }\n    finally\n    {\n        // This block is optional. \n        // Use the finally-block if you need to clean things up or similar\n        Log.CloseAndFlush();\n    }\n}\n'})}),"\n",(0,o.jsx)(n.h2,{id:"exceptions-from-another-thread",children:"Exceptions from another thread"}),"\n",(0,o.jsxs)(n.p,{children:["If you are using ",(0,o.jsx)(n.code,{children:"Task"}),"s to run some work asynchronously, you can setup ",(0,o.jsx)(n.code,{children:"TaskScheduler.UnobservedTaskException"}),". For more information read the ",(0,o.jsx)(n.a,{href:"https://docs.microsoft.com/dotnet/api/system.threading.tasks.taskscheduler.unobservedtaskexception",children:"Microsoft .NET-Documentation"}),"."]}),"\n",(0,o.jsx)(n.h2,{id:"exceptions-from-reactive-ui",children:"Exceptions from Reactive UI"}),"\n",(0,o.jsxs)(n.p,{children:["If you are using Avalonia together with ",(0,o.jsx)(n.a,{href:"../guides/basics/mvvm#frameworks",children:"ReactiveUI"}),", you can subscribe to their ",(0,o.jsx)(n.code,{children:"RxApp.DefaultExceptionHandler"}),". For more information please refer to ",(0,o.jsx)(n.a,{href:"https://www.reactiveui.net/docs/handbook/default-exception-handler/",children:"ReactiveUI Default Exception Handler"}),"."]}),"\n",(0,o.jsxs)(n.p,{children:["Note, ",(0,o.jsx)(n.code,{children:"RxApp.DefaultExceptionHandler"})," should be set before any ReactiveCommand was created. Otherwise, custom handler won't be used.\nYou can set it in your application entry point or before any Avalonia view or window was created."]})]})}function h(e={}){const{wrapper:n}={...(0,a.a)(),...e.components};return n?(0,o.jsx)(n,{...e,children:(0,o.jsx)(l,{...e})}):l(e)}},11151:(e,n,t)=>{t.d(n,{Z:()=>s,a:()=>r});var o=t(67294);const a={},i=o.createContext(a);function r(e){const n=o.useContext(i);return o.useMemo((function(){return"function"==typeof e?e(n):{...n,...e}}),[n,e])}function s(e){let n;return n=e.disableParentContext?"function"==typeof e.components?e.components(a):e.components||a:r(e.components),o.createElement(i.Provider,{value:n},e.children)}}}]);